# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your repo
      - uses: actions/checkout@v4

      # 2) Setup Node.js and cache Yarn deps
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      # 3) Install dependencies (respects yarn.lock)
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4) Lint
      - name: Lint
        run: yarn lint

      # 5) Type-check
      - name: Type-check
        run: yarn typecheck

      # 6) Run tests with coverage
      - name: Run tests
        run: yarn test --coverage

      # 7) Upload coverage to Codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          flags: unittests
